
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PCA_Addin
{
    /// <summary>
    ///Purpose: comparisons object lists -- Generated by user 
    /// </summary>
    public class cls_TTestTables
    {
        // list of Ttest tabels
        public List<cls_Comparison> Lst_Comp;

        //string table name
        string TableName;

        //table name property 
        public string Table_name
        {
            get 
            { return TableName;} 
            set 
            {TableName = value;} 
        }

        /// <summary>
        /// Purpose: constructor for compareisons 
        /// </summary>
        public cls_TTestTables()
        {
            Lst_Comp = new List<cls_Comparison>();// list of all the tables curently availble 
         
        }

        /// <summary>
        /// Purpose: constructor passing a string value so we can give the table a specific name 
        /// </summary>
        /// <param name="Tname"></param>
        public cls_TTestTables(string Tname)
        {
            Lst_Comp = new List<cls_Comparison>();// list of all the tables curently availble 
            TableName = Tname;//table name
        }

    }
}
