
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PCA_Addin
{
    /// <summary>
    /// Purpose: Global class with whitch we create a series of lists to hold class objects we can choose to call on from anywhere in our program 
    /// </summary>
    public class cls_QT
    {
        // global object list 
        public List<cls_PCA_File> Lst_File;// for the data from rows in our txt file 2nd section

        public List<cls_Metabolite_Files> Lst_Metabolite;// stores the data for the shifts and metabolite name

        public List<cls_Group_Files_Data> Lst_Group;// stores the groups info data -- generated by user

        public List<cls_TTestTables> Lst_Table;// stores the tables of comparison data

        public List<cls_Comparison> Lst_Comp;// stores comparisons that allow us to avoid data overlap 

        public List<cls_Results> Lst_Results;// stores all the results 

        public List<string> headers_for_QT;// stores the headers at the top of the reported data

        public List<string> extra_Text; // stores the additional txt at the top of the reported data

        /// <summary>
        /// Purpose: constructor to set values
        /// </summary>
        public cls_QT()
        {
            //initilize all List's
            Lst_File = new List<cls_PCA_File>();

            Lst_Metabolite = new List<cls_Metabolite_Files>();

            Lst_Group = new List<cls_Group_Files_Data>(); 

            Lst_Table = new List<cls_TTestTables>();

            Lst_Results = new List<cls_Results>();

            headers_for_QT = new List<string>();

            Lst_Comp = new List<cls_Comparison>(); 

          extra_Text = new List<string>(); // 
        }

    }//end of class
}//end of namespace 
